// <auto-generated />
using ChartApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChartApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChartApi.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SalesRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Month = "Jan",
                            SalesAmount = 12000.00m
                        },
                        new
                        {
                            Id = 2,
                            Month = "Feb",
                            SalesAmount = 18000.00m
                        },
                        new
                        {
                            Id = 3,
                            Month = "Mar",
                            SalesAmount = 15000.00m
                        },
                        new
                        {
                            Id = 4,
                            Month = "Apr",
                            SalesAmount = 22000.00m
                        },
                        new
                        {
                            Id = 5,
                            Month = "May",
                            SalesAmount = 26000.00m
                        },
                        new
                        {
                            Id = 6,
                            Month = "Jun",
                            SalesAmount = 30000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
