# Generated by Django 6.1 on 2026-08-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
