# Generated by Django 6.0.5 on 2026-06-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('sales', models.IntegerField()),
                ('expenses', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Monthly Sale',
                'verbose_name_plural': 'Monthly Sales',
                'ordering': ['id'],
            },
        ),
    ]
